# =============================================================================
# Production Docker Compose for recruitment backend
# =============================================================================
# Use this file for production deployments
# Command: docker-compose up -d
#
# Ensure environment variables are set securely and not hardcoded in production
# =============================================================================

services:
  recruitment-backend:
    image: ghcr.io/computersocietyvitc/recruitment-backend:master
    ports:
      - "9999:8080"
    environment:
      - ENV=production
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=recruitment_user
      - DB_PASSWORD=recruitment_password
      - DB_NAME=recruitment_db
      - DB_MAX_CONNS=25
      - DB_MIN_CONNS=5
      - JWT_SECRET=bzRPnIXW+fX6niA0mK9RKV6nMRVNVtcCMl1Atym9NEI=
      - JWT_EXPIRY_DURATION=24h
      - EMAIL_VERIFICATION_OTP_DURATION=10m
      - PASSWORD_RESET_OTP_DURATION=30m
      - ADMIN_EMAIL=admin@comp.socks
      - ADMIN_PASSWORD=Admin@12345
      - ADMIN_PHONE=+911000000000
      - TRUSTED_PROXIES=172.16.0.0/12
      - CORS_ALLOWED_ORIGINS=https://join.ieeecsvitc.com
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=587
      - SMTP_USER=johndoe
      - SMTP_PASSWORD=PHtE6r0EQby5
      - EMAIL_FROM=recruitment@no-reply.ieeecsvitc.com
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: recruitment_db
      POSTGRES_USER: recruitment_user
      POSTGRES_PASSWORD: recruitment_password
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - /var/data/recruitment_prod/db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-recruitment_user} -d ${DB_NAME:-recruitment_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true
    # Don't expose port in production unless needed for external access
    # ports:
    #   - "5432:5432"
